<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="OperateScopeManage.aspx.cs" Inherits="AuthorizationManage_OperateScope"
     Culture="Auto" UICulture="Auto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table>
        <tr>
            <td valign="top">
                <div class="title3" style="width: 490px;">
                    <asp:Label runat="server" meta:resourcekey="Title_Label"></asp:Label>
                </div>
                <div class="BorderedArea" style="overflow: auto; width: 500px; height: 400px">
                    <asp:TreeView ID="PositionTreeView" runat="server" AutoGenerateDataBindings="False"
                        ExpandDepth="1" OnSelectedNodeChanged="PositionTreeView_SelectedNodeChanged"
                        ShowLines="True">
                        <HoverNodeStyle BackColor="Gray" />
                        <SelectedNodeStyle BackColor="#000040" ForeColor="White" />
                    </asp:TreeView>
                </div>
            </td>
            <td style="width: 10px;">
                &nbsp;
            </td>
            <td valign="top">
                <asp:UpdatePanel ID="OperateUpdatePanel" UpdateMode="conditional" Visible="false"
                    runat="server">
                    <ContentTemplate>
                        <div class="title4" style="width: 340px;">
                            <asp:Label runat="server" meta:resourcekey="Title_Label1"></asp:Label>
                        </div>
                        <gc:GridView ID="OperateGridView" runat="server" AutoGenerateColumns="False" CssClass="GridView"
                            DataSourceID="OperateDS" DataKeyNames="BusinessOperateId" OnSelectedIndexChanged="OperateGridView_SelectedIndexChanged"
                            AllowPaging="True" AllowSorting="True" OnPageIndexChanging="OperateGridView_PageIndexChanging"
                            OnRowDataBound="OperateGridView_RowDataBound" PageSize="15" OnDataBinding="OperateGridView_DataBinding"
                            OnDataBound="OperateGridView_DataBound">
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="OperateCheckBox" Visible="<%# HasManageRight %>" runat="server" />
                                    </ItemTemplate>
                                    <HeaderTemplate>
                                        <asp:CheckBox ID="AllOperateCheckBox" Visible="<%# HasManageRight %>" AutoPostBack="true"
                                            runat="server" OnCheckedChanged="AllOperateCheckBox_CheckedChanged" />
                                    </HeaderTemplate>
                                    <ItemStyle Width="30px" HorizontalAlign="Center" />
                                </asp:TemplateField>
                                <asp:BoundField DataField="BusinessOperateId" HeaderText="BusinessOperateId" ReadOnly="True"
                                    SortExpression="BusinessOperateId" Visible="False" />
                                <asp:BoundField DataField="BusinessUseCaseName" meta:resourcekey="OperateGridView_Template_UseCaseName"
                                    SortExpression="BusinessUseCaseName">
                                    <ItemStyle Width="170px" HorizontalAlign="Center" />
                                </asp:BoundField>
                                <asp:TemplateField meta:resourcekey="OperateGridView_Template_OperateName" SortExpression="BusinessOperateName">
                                    <ItemTemplate>
                                        <asp:LinkButton CommandName="Select" ID="LinkButton1" Text='<%# Bind("BusinessOperateName") %>'
                                            runat="server"></asp:LinkButton>
                                    </ItemTemplate>
                                    <ItemStyle Width="157px" HorizontalAlign="Center" />
                                </asp:TemplateField>
                            </Columns>
                            <HeaderStyle CssClass="Header" />
                            <SelectedRowStyle BackColor="#C0C000" />
                        </gc:GridView>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
            <td style="width: 10px;">
                &nbsp;
            </td>
            <td valign="top">
                <asp:UpdatePanel ID="UpdatePanel1" UpdateMode="conditional" runat="server">
                    <ContentTemplate>
                        <div id="ScopeDIV" runat="server" visible="false">
                            <div class="title4" style="width: 340px;">
                                <asp:Label runat="server" meta:resourcekey="Title_Label2"></asp:Label>
                            </div>
                            <div class="BorderedArea" style="width: 350px; height: 400px; overflow: auto;">
                                <asp:TreeView ID="ScopeTreeView" runat="server" AutoGenerateDataBindings="False"
                                    ExpandDepth="2" ShowLines="True" ShowCheckBoxes="all">
                                    <HoverNodeStyle BackColor="Gray" />
                                    <SelectedNodeStyle BackColor="#000040" ForeColor="White" />
                                </asp:TreeView>
                            </div>
                            <div style="text-align: center;">
                                <asp:Button ID="SetScopeBtn" meta:resourcekey="OpeeateScope_Button_SetOperateScope"
                                    CssClass="button_big" runat="server" OnClick="SetScopeBtn_Click" />
                            </div>
                        </div>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
    </table>
    <asp:UpdatePanel ID="ScopeListUpdatePanel" Visible="false" UpdateMode="Conditional"
        runat="server">
        <ContentTemplate>
            <asp:Panel ID="ScopeListPanel" Visible="false" runat="Server">
                <div class="title">
                    <asp:Label runat="server" meta:resourcekey="Title_Label3"></asp:Label>
                </div>
                <gc:GridView ID="ScopeListGridView" runat="server" AutoGenerateColumns="False" DataKeyNames="OperateScopeId"
                    DataSourceID="PositionOperateScopeDS" CssClass="GridView" OnRowDataBound="ScopeListGridView_RowDataBound">
                    <Columns>
                        <asp:TemplateField meta:resourcekey="OperateGridView_Template_OUName" SortExpression="ScopeOrganziationUnitId">
                            <ItemTemplate>
                                <asp:LinkButton ID="ScopedOULinkButton" runat="server" OnClick="ScopedOULinkButton_Click"></asp:LinkButton>
                            </ItemTemplate>
                            <ItemStyle HorizontalAlign="Center" Width="1270px" />
                        </asp:TemplateField>
                    </Columns>
                    <HeaderStyle CssClass="Header" />
                    <EmptyDataTemplate>
                        <table>
                            <tr class="Header">
                                <td class="Empty1" style="width: 1270px;">
                                    <asp:Label runat="server" meta:resourcekey="Label_Title"/>
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align: center;" class="Empty2 noneLabel">
                                    <asp:Label runat="server" Text='<%$Resources:Common,Label_None %>'/>
                                </td>
                            </tr>
                        </table>
                    </EmptyDataTemplate>
                </gc:GridView>
            </asp:Panel>
        </ContentTemplate>
    </asp:UpdatePanel>
    <asp:ObjectDataSource ID="PositionOperateScopeDS" runat="server" SelectMethod="GetOperateScope"
        TypeName="BusinessObjects.AuthorizationBLL">
        <SelectParameters>
            <asp:Parameter Name="positionId" Type="Int32" />
            <asp:Parameter Name="businessOperateId" Type="Int32" />
        </SelectParameters>
    </asp:ObjectDataSource>
    <asp:SqlDataSource ID="OperateDS" runat="server" ConnectionString="<%$ ConnectionStrings:ERSConnectionString %>"
        SelectCommand="SELECT distinct [BusinessOperateId], [BusinessOperateName], [BusinessOperateDescription], [BusinessUseCaseId], [BusinessUseCaseName], [BusinessUseCaseDescription], [PositionId] FROM [PositionEnabledOperateView] WHERE ([PositionId] = @PositionId) AND ([BusinessUseCaseId] < 100) AND ([BusinessOperateId] > 2000 and [BusinessOperateId] < 4000 ) order by BusinessUseCaseId">
        <SelectParameters>
            <asp:Parameter Name="PositionId" Type="Int32" />
        </SelectParameters>
    </asp:SqlDataSource>
</asp:Content>
