<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="PositionRightManage.aspx.cs" Inherits="AuthorizationManage_PositionRightManage"
     Culture="Auto" UICulture="Auto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table width="1240px" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td valign="top" style=" width:624px; padding-left:10px;">
                <div class="title2" style="width: 610px;">
                    <asp:Label runat="server" meta:resourcekey="Position_Title_Label"></asp:Label></div>
                <div style="width: 624; height: 600px; overflow: auto;">
                    &nbsp;<asp:TreeView ID="OrganizationTreeView" runat="server" ExpandDepth="2" OnSelectedNodeChanged="OrganizationTreeView_SelectedNodeChanged"
                        AutoGenerateDataBindings="False" ShowLines="True">
                        <SelectedNodeStyle BackColor="#000040" ForeColor="White" />
                        <HoverNodeStyle BackColor="Gray" />
                    </asp:TreeView>
                </div>
            </td>
            <td style="width:570px; padding-left:10px;" valign="top">
                <asp:UpdatePanel ID="RoleUpdatePanel" UpdateMode="Conditional" runat="server">
                    <ContentTemplate>
                        <div class="title3" style="width: 560px;">
                            <asp:Label runat="server" meta:resourcekey="Position_Title_Label1"></asp:Label>
                        </div>
                        <gc:GridView ID="SystemRoleGridView" CssClass="GridView" runat="server" AutoGenerateColumns="False"
                            DataKeyNames="SystemRoleId" DataSourceID="SystemRoleDS">
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="SystemRoleCheckBox" runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="SystemRoleId" HeaderText="SystemRoleId" InsertVisible="False"
                                    ReadOnly="True" SortExpression="SystemRoleId" Visible="False" ItemStyle-HorizontalAlign="Center" />
                                <asp:BoundField DataField="SystemRoleName" meta:resourcekey="SystemRoleGridView_TemplateField_SystemRoleName" SortExpression="SystemRoleName"
                                    ItemStyle-Width="220px" ItemStyle-HorizontalAlign="Center" />
                                <asp:BoundField DataField="Description" meta:resourcekey="SystemRoleGridView_TemplateField_Remark" SortExpression="Description"
                                    ItemStyle-Width="328px" ItemStyle-HorizontalAlign="Center" />
                            </Columns>
                            <HeaderStyle CssClass="Header" />
                        </gc:GridView>
                        <asp:SqlDataSource ID="SystemRoleDS" runat="server" ConnectionString="<%$ ConnectionStrings:ERSConnectionString %>"
                            SelectCommand="SELECT [SystemRoleId], [SystemRoleName], [Description] FROM [SystemRole]">
                        </asp:SqlDataSource>
                        <div style="text-align: center;">
                            <asp:Button ID="SetPositionRightBtn" Enabled="false" runat="server" CssClass="button_wider"
                                OnClick="SetPositionRightBtn_Click"  meta:resourcekey="Position_Button_SetPosition" />
                        </div>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
    </table>
</asp:Content>
